<a href="https://colab.research.google.com/github/carloshsieh22/careercoachai/blob/main/DATASCI_112_Final_Project_Carlos_Allison_Music_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Extracting the Music and Processing Medley Skates

Some skaters skate to multiple different songs with different genres. This scrapes the competition websites to build the SP Music dataframe and the FS Music dataframe.

In [ ]:
import pandas as pd
music_df = pd.read_csv('music_df.csv')

In [ ]:
music_df

,Unnamed: 0,Skater Name,SP Music,FS Music
0,0,LIU Alysa,['Promise by Laufey'],['MacArthur Park Suite by Donna Summer']
1,1,SAKAMOTO Kaori,['Time To Say Goodbye performed by Sarah Brigh...,"['La vie en rose by Patricia Kaas, Édith Piaf'..."
2,2,NAKAI Ami,['La Strada by Nino Rota'],"['What a Wonderful World by Lexi Walker, The P..."
3,3,CHIBA Mone,"['Last Dance by Donna Summer, Giorgio Moroder,...","['A Thousand Times Goodnight (from ""Romeo and ..."
4,4,GLENN Amber,['Like A Prayer by Madonna'],"['I Will Find You by Audiomachine', 'The Retur..."
...,...,...,...,...
310,310,Jakub LOFEK,['Cold by Jonathan Roy feat. Kim Richardson'],"['Pure Imagination (from ""Wonka"" soundtrack) b..."
311,311,Alp Eren OZKAN,['Red Right Hand by Nick Cave and the Bad Seed...,"['The World Is Not Enough (from ""James Bond"" s..."
312,312,Kevin AYMOZ,"['Le Lac by Jean-Michel Blais', 'Judas by Lady...","['Boléro, m. 81 by Maurice Ravel']"
313,313,Alexander ZLATKOV,['Nureyev (from “The White Crow”) by Lisa Bati...,['Mala Luna by Gino Vannelli']
314,314,David SEDEJ,['Asturias (from Suite Española) by The Six St...,"['The Great Adventure by Rok Nardin', 'The Mad..."

In [ ]:
import ast
music_df['FS Music'] = music_df['FS Music'].apply(ast.literal_eval)
df_fs_exploded = music_df.explode('FS Music')[['Skater Name', 'FS Music']].rename(columns={'FS Music': 'Song'})

music_df['SP Music'] = music_df['SP Music'].apply(ast.literal_eval)
df_sp_exploded = music_df.explode('SP Music')[['Skater Name', 'SP Music']].rename(columns={'SP Music': 'Song'})

In [ ]:
df_sp_exploded

           Skater Name                                               Song
0            LIU Alysa                                  Promise by Laufey
1       SAKAMOTO Kaori  Time To Say Goodbye performed by Sarah Brightm...
2            NAKAI Ami                             La Strada by Nino Rota
3           CHIBA Mone  Last Dance by Donna Summer, Giorgio Moroder, P...
4          GLENN Amber                           Like A Prayer by Madonna
..                 ...                                                ...
312        Kevin AYMOZ                        Le Lac by Jean-Michel Blais
312        Kevin AYMOZ                                 Judas by Lady Gaga
313  Alexander ZLATKOV  Nureyev (from “The White Crow”) by Lisa Batias...
314        David SEDEJ  Asturias (from Suite Española) by The Six Stri...
314        David SEDEJ                                   Carmen by Marcin

[434 rows x 2 columns]

In [ ]:
df_sp_exploded[~df_sp_exploded['Song'].str.contains('by')]

            Skater Name                                               Song
30        KAGIYAMA Yuma                      I Wish (Figure Skating Remix)
35     SIAO HIM FA Adam                                 Leonardo da Vinci:
50     CARRILLO Donovan              Hip Hip Chin Chin (Smooth Return Mix)
71     Adam SIAO HIM FA                                 Leonardo da Vinci:
80       Luc ECONOMIDES                                              Selah
127      Luc ECONOMIDES                                              Selah
142       Yuma KAGIYAMA                      I Wish (Figure Skating Remix)
188       Yuma KAGIYAMA                      I Wish (Figure Skating Remix)
189    Adam SIAO HIM FA                                 Leonardo da Vinci:
206   Gabrielle DALEMAN  El Tango De Roxanne -  Ewan McGregor, Jose Fel...
236    Donovan CARRILLO              Hip Hip Chin Chin (Smooth Return Mix)
280  Anastasia GRACHEVA                                            Eronika
288   Georgii RESHTENKO                               Scratch (feat.Duomo)
311      Alp Eren OZKAN                                         Karate Kid

In [ ]:
df_fs_exploded[~df_fs_exploded['Song'].str.contains('by')]

             Skater Name                                             Song
8    GUBANOVA Anastasiia    Unchained Melody (from "Ghost - The Musical")
8    GUBANOVA Anastasiia     The Love Inside (from "Ghost - The Musical")
8    GUBANOVA Anastasiia    Unchained Melody (from "Ghost - The Musical")
19    KURAKOVA Ekaterina           Sparkling Diamonds (from Moulin Rouge)
19    KURAKOVA Ekaterina                Come What May (from Moulin Rouge)
23         SENIUK Mariia             Opening Theme from "Stranger Things"
30         KAGIYAMA Yuma                 Turandot: Christopher Tin Finale
35      SIAO HIM FA Adam                            The Creation of Adam:
42       BRITSCHGI Lukas                      Journey through the Orient:
45            JIN Boyang                                 Perfect Symphony
52           HAGARA Adam              007 James Bond Theme (epic version)
52           HAGARA Adam    007 (James Bond Theme) (epic trailer version)
54         KIM Hyungyeom                    Suite from Lawrence Of Arabia
67             Lea SERNA                                  Hymne a l’amour
71      Adam SIAO HIM FA                            The Creation of Adam:
73       Lukas BRITSCHGI                      Journey through the Orient:
80        Luc ECONOMIDES                                   Claire de lune
89         Mariia SENIUK             Opening Theme from "Stranger Things"
108  Anastasiia GUBANOVA    Unchained Melody (from "Ghost - The Musical")
108  Anastasiia GUBANOVA     The Love Inside (from "Ghost - The Musical")
108  Anastasiia GUBANOVA    Unchained Melody (from "Ghost - The Musical")
110        Starr ANDREWS                             Fantasy of Happiness
110        Starr ANDREWS                         Interview with a Vampire
112            Lea SERNA                                  Hymne a l’amour
115   Ekaterina KURAKOVA           Sparkling Diamonds (from Moulin Rouge)
115   Ekaterina KURAKOVA                Come What May (from Moulin Rouge)
121          Jason BROWN                Say Something (A Great Big World)
127       Luc ECONOMIDES                                   Claire de lune
142        Yuma KAGIYAMA                 Turandot: Christopher Tin Finale
144      Lukas BRITSCHGI                      Journey through the Orient:
145           Boyang JIN                                 Perfect Symphony
147          Adam HAGARA              007 James Bond Theme (epic version)
147          Adam HAGARA    007 (James Bond Theme) (epic trailer version)
157  Anastasiia GUBANOVA    Unchained Melody (from "Ghost - The Musical")
157  Anastasiia GUBANOVA     The Love Inside (from "Ghost - The Musical")
157  Anastasiia GUBANOVA    Unchained Melody (from "Ghost - The Musical")
169           Boyang JIN                                 Perfect Symphony
188        Yuma KAGIYAMA                 Turandot: Christopher Tin Finale
189     Adam SIAO HIM FA                            The Creation of Adam:
192          Jason BROWN                Say Something (A Great Big World)
214        Starr ANDREWS                             Fantasy of Happiness
214        Starr ANDREWS                         Interview with a Vampire
227           Boyang JIN                                 Perfect Symphony
238        Hyungyeom KIM                    Suite from Lawrence Of Arabia
252  Anastasiia GUBANOVA    Unchained Melody (from "Ghost - The Musical")
252  Anastasiia GUBANOVA     The Love Inside (from "Ghost - The Musical")
252  Anastasiia GUBANOVA    Unchained Melody (from "Ghost - The Musical")
256   Ekaterina KURAKOVA           Sparkling Diamonds (from Moulin Rouge)
256   Ekaterina KURAKOVA                Come What May (from Moulin Rouge)
262            Lea SERNA                                  Hymne a l’amour
268        Mariia SENIUK             Opening Theme from "Stranger Things"
274    Antonina DUBININA          Twiling Huntress feat. Merethe Soltvedt
289      Lukas BRITSCHGI                      Journey through the Orient:
295          Adam HAGARA              007 James Bond Theme (epic version)
295          Adam HAGARA    007 (James Bond Theme) (epic trailer version)
311       Alp Eren OZKAN  From Russia With Love ("James Bond" soundtrack)

In [ ]:
df_fs_exploded[df_fs_exploded['Song'].str.contains('Musical')]
musicals = ['Ghost', 'Dracula', 'from "Ghost - The Musical"'],

             Skater Name                                               Song
8    GUBANOVA Anastasiia      Unchained Melody (from "Ghost - The Musical")
8    GUBANOVA Anastasiia       The Love Inside (from "Ghost - The Musical")
8    GUBANOVA Anastasiia      Unchained Melody (from "Ghost - The Musical")
108  Anastasiia GUBANOVA      Unchained Melody (from "Ghost - The Musical")
108  Anastasiia GUBANOVA       The Love Inside (from "Ghost - The Musical")
108  Anastasiia GUBANOVA      Unchained Melody (from "Ghost - The Musical")
157  Anastasiia GUBANOVA      Unchained Melody (from "Ghost - The Musical")
157  Anastasiia GUBANOVA       The Love Inside (from "Ghost - The Musical")
157  Anastasiia GUBANOVA      Unchained Melody (from "Ghost - The Musical")
164               Yi ZHU  Ghost -The Musical by Glen Ballard, Alex North...
211               Yi ZHU  Ghost -The Musical by Glen Ballard, Alex North...
252  Anastasiia GUBANOVA      Unchained Melody (from "Ghost - The Musical")
252  Anastasiia GUBANOVA       The Love Inside (from "Ghost - The Musical")
252  Anastasiia GUBANOVA      Unchained Melody (from "Ghost - The Musical")
277  Nargiz SUELEYMANOVA  Dracula The Musical by Frank Widhorn, Don Blac...

# Classifying the different songs manually

In [ ]:
sp_mapping = {
    'warhorse': [
        "Adiós Nonino by Astor Piazzolla, Héctor Ulises Passarella (bandoneón)",
        "Asturias (from Suite Española) by The Six String Collective",
        "Carmen by Marcin",
        "Clouds, The Mind on the (Re)Wind by Ezio Bosso",
        "Czardas Caprice by Ilan Rechtman, Lara St.Jonh",
        "Czardas by Sarah Nemtanu, Chilly Gonzales",
        "Experience by Ludovico Einaudi, Daniel Hope, I Virtuosi Italiani",
        "La Strada by Nino Rota",
        "Lux Aeterna by Christopher Tin",
        "Malaguena by Ernesto Lecuona",
        "Nocturne No. 20 by Frédéric Chopin",
        "Nocturne No.20 C sharp minor by Frédéric Chopin",
        "Otono Porteno by Astor Piazzolla",
        "Prelude No. 2 in C sharp minor by Sergei Rachmaninov",
        "Rain, In Your Black Eyes by Ezio Bosso",
        "Run by Ludovico Einaudi",
        "Sirens by Christopher Tin",
        "Suite Bergamasque 82: Ill. Clair de Lune by Claude Debussy",
        "Tango Amore by Astor Piazzolla",
        "Winter 2: The Four Seasons, Violin Concerto in F minor Allegro by Antonio Vivaldi",
        "Winter 3: The Four Seasons, Violin Concerto in F minor Allegro by Antonio Vivaldi",
        "The Nutcracker by Petr Ilyich Tchaikovski",
        "Waltz 1805 by Edgar Hakobyan",
        "Yo soy Maria by Astor Piazzolla",
    ],
    'movie/musical': [
        'Almost In Your Arms (from "Houseboat" soundtrack) by Sophia Loren, Jay Livingston, Ray Evans',
        'Ballata per Enrico (from "Tango per la libertà" soundtrack) by Stefano Lentini',
        'Beatrice (La Legge Di Lidia Poët soundtrack) by Massimiliano Mechelli',
        'Canto Muto (from "Tango per la libertà" soundtrack) by Stefano Lentini',
        "C'è Qualcosa Che Devi Dirmi (La Legge Di Lidia Poët soundtrack) by Massimiliano Mechelli",
        "Dark Night - Kara (Detroit Become Human soundtrack) by Philip Sheppard",
        "Eclipse (Dune soundtrack) by Hans Zimmer",
        "El Tango De Roxanne (from Moulin Rouge soundtrack) by Ewan McGregor, José Feliciano, Jacek Koman, Sting, Mariano Mores",
        "El Tango De Roxanne - Ewan McGregor, Jose Feliciano, Jacek Koman, Sting, Baz Luhrmann, Mariano Mores",
        "El Tango de Roxanne by José Feliciano, Ewan McGregor & Jacek Koman",
        'Fantasy for Violin and Orchestra (from "Ladies in Lavender") by Joshua Bell, Nigel Hess',
        "Game of Thrones Medley performed by Atin Piano",
        'Grasslands Chant (from "The Lion King") by Lebo M',
        "Il Postino (soundtrack) by Josh Groban, Luis Bacalov",
        'My Heart Will Go On (from "Titanic") by James Horner, performed by Celine Dion',
        "Nitti (La Legge Di Lidia Poët soundtrack) by Massimiliano Mechelli",
        "Nulla è Risolto (La Legge Di Lidia Poët soundtrack) by Massimiliano Mechelli",
        'Nureyev (from "The White Crow") by Lisa Batiashvili, Ilan Eshkeri',
        'Plaza de Mayo (from "Tango per la libertà" soundtrack) by Stefano Lentini',
        'Remember (from "The Lion King") by Hans Zimmer',
        "Send In the Clowns performed by Susan Boyle",
        "Sparkling Diamonds by Nicole Kidman, Jim Broadbent, Lara Mulcahy, Caroline O'Connor & Natalie Mendoza",
        'Spirit (from "The Lion King") by Beyonce, Ilya Salmanzadeh, Timothy Lee McKenzie',
        'Tango per la libertà (from "Tango per la libertà" soundtrack) by Stefano Lentini',
        'Unchained Melody (from "Ghost") by Alex North, Hy Zaret',
        "With One Look by Andrew Lloyd Webber, Patti LuPone",
        "Worm Army (Dune soundtrack) by Hans Zimmer",
        'Zou Bisou Bisou (from "The Millionaires" soundtrack) by Sophia Loren, Bill Shepherd, Alan Tew',
        'C’è Qualcosa Che Devi Dirmi (La Legge Di Lidia Poët soundtrack) by Massimiliano Mechelli',
        'Nureyev (from “The White Crow”) by Lisa Batiashvili, Ilan Eshkeri'
    ],
    'pop_contemporary': [
       'N’insiste pas by Camille Lellouche',
       'Hey Pachucho! by \xa0Royal Crown Revue',
       "I''m That Girl by Beyoncé",
       'I Got You (I Feel Good) by Jamhe Famous Flameses Brown & Theron Thomas, James Brown',
       'The Game Is Afoot by \u200eEternal Eclipse',
       'Fate of the Clockmaker by \u200eEternal Eclipse',
       'El Tango De Roxanne - \xa0Ewan McGregor, Jose Feliciano, Jacek Koman, Sting, Baz Luhrmann, Mariano Mores',
       'Moriarty\xa0 (feat. Sebastian Pecznik & Duomo) by Power-Haus',
       'L’enfer by Stromae, arr. by Cédric Tour',
        "13 Beaches by Lana Del Rey",
        "A Stutter by Olafur Arnalds f. Arnor Dan",
        "Alba Lullaby by Maksim, Tonči Huljić",
        "Alien Superstar by Beyoncé",
        "Amor Congelado by District 78, Chris Lightbody, Spencer Yaras, Robert Steinmiller",
        "Andrei by Luca D'Alberto",
        "Angels by Jessica Simpson, Robbie Williams, Guy Chambers",
        "Anniversary by Yoshiki",
        "Another Love by Dimitri Vangelis & Wyman Remix",
        "Another Love by Tom Odell",
        "Arrow by The Irrepressibles",
        "Asteromata by Arcade and Klavdia",
        "Back from the Edge by James Arthur",
        "Battle Without Honor Or Humanity by Hotei",
        "Besame Mucho by J2 (feat. Ilza)",
        "Billie Jean by Michael Jackson",
        "Bodies Main Title by Jon Opstad",
        "Born For This by Foxxi",
        "Break My Soul by Beyoncé",
        "Broken Vow by Lara Fabian, Walter Afanasieff",
        "Caravanserai by Karunesh",
        "Carol Ann by Michael W. Smith",
        "Caruso by Jackie Evancho, Lucio Dalla",
        "Chasing Cars by Snow Patrol, Tommee Profitt, Fleurie",
        "Cold by Chris Stapleton",
        "Cold by Jonathan Roy feat. Kim Richardson",
        "Color Me (Julia Holter Remix) by Active Child",
        "Color Me by Active Child",
        "Conquest of Spaces by Woodkid",
        "Coupure Électrique by Britney Spears",
        "Criminal Tango by Dinamika Ensemble, Nathalie Bonin, Simone Benyacar",
        "Devil May Cry by Sofiane Pamart",
        "Did You Ever Feel Lonely? by Gary Moore",
        "Dies Irae by Náttúra featuring Vila",
        "Dig Down by Muse arranged by Cédric Tour",
        "Dirty Paws by Of Monsters and Men",
        "Don't Let Me Be Misunderstood by Santa Esmeralda, RZA, Bennie Benjamin",
        "Dracula (Nate Sees Cassie) by Labrinth",
        "Earth Song by Michael Jackson",
        "East of Eden by Lee Holdridge",
        "Eronika",
        "Exercises in Free Love by Freddie Mercury, Mike Moran",
        "Fall On Me by Andrea Bocelli, Matteo Bocelli",
        "Fate of the Clockmaker by Eternal Eclipse",
        "Finesse by Bruno Mars",
        "Fought & Lost (feat. Brian May) by Sam Ryder, Brian May",
        "Free Bird by Lynyrd Skynyrd",
        "Freedom by Pharell Williams",
        "Freestyler by Bomfunk MC's",
        "Frozen by Madonna",
        "Girl With One Eye by Florence + The Machine",
        "Glimpse of Us by Joji",
        "Hey Pachucho! by Royal Crown Revue",
        "Higher by Reinaeiry",
        "Hip Hip Chin Chin (Smooth Return Mix)",
        "Hip-Hip Chin Chin (Yaziko Club Mix) by Maixm Illion",
        "How It Ends by DeVotchKa",
        "I Got You (I Feel Good) by James Brown & Theron Thomas",
        "I Knew I Loved You by Le Muse",
        "I Put A Spell On You by Kandace Springs, David Sanborn",
        "I Surrender by Celine Dion",
        "I Will Always Love You by Whitney Houston, David Foster",
        "I Wish (Figure Skating Remix)",
        "I'm That Girl by Beyoncé",
        "Iron Sky by Paolo Nutini",
        "Ironside Theme by Quincy Jones",
        "Is It Love (Apple Music Home Session) by Loreen",
        "Is This Now by Florian Christl",
        "Isa by Wardruna",
        "It's Wonderful by Roberto Danova, Angelo Camassa",
        "Jacquadi by Polo & Pan",
        "Je te laisserai des mots by Patrick Watson",
        "Jezebel (remastered) by Sade",
        "Judas by Lady Gaga",
        "Karate Kid",
        "Kiss by Prince",
        "La terre vue du ciel by Armand Amar arr. by Cedric Tour",
        "Last Dance by Donna Summer, Giorgio Moroder, Pete Bellotte",
        "Le Lac by Jean-Michel Blais",
        "Leonardo da Vinci:",
        "Les parapules de Cherbourg by Michel Legrand",
        "Like A Prayer by Madonna",
        "Love The Hell Out Of You by Lewis Capaldi",
        "L'enfer by Stromae, arr. by Cédric Tour",
        "Making Music by Zakir Hussain",
        "Maybe I Maybe You by Scorpions",
        "Mephisto's Lullaby by Xtortion Audio",
        "Moriarty (feat. Sebastian Pecznik & Duomo) by Power-Haus",
        "Mosaic by Billy Esteban, Ghenwa Nemnom & Cafe de Anatolia",
        "Mugzy's Move by Royal Crown Revue",
        "My Love by Sharon Kovacs",
        "My Sweet and Tender Beast by Evgeni Doga",
        "My Way by Chris Mann",
        "N'insiste pas by Camille Lellouche",
        "No Good by Kaleo",
        "Objection (Tango) by Shakira",
        "On My Mind by Mergui",
        "Papaya (Minions Remix) by The Funny Minions",
        "Pearls (remastered) by Sade",
        "People Get Up and Drive Your Funky Soul by James Brown",
        "Peponi (Paradise) by The Piano Guys, Alex Boyé",
        "Pon de Floor by Major Lazer, Afro Jack",
        "Promise by Laufey",
        "Punga by Klingande",
        "Purple Rain by Prince",
        "Qui a le droit by Santa",
        "Ray Of Light by Madonna",
        "Reckoning Song (In A Box III Version) by Asaf Avidan",
        "Red Right Hand by Nick Cave and the Bad Seeds",
        "Reel Around the Sun by Bill Whelan",
        "Reminiscence by Jacub Pietras",
        "Rescue by Lauren Daigle",
        "Rumination by Baandit",
        "Run the World by Beyoncé",
        "San Sanana by Any Malik, Alka Yagnik & Hema Sardesai",
        "Santa Maria (Del Buen Ayre) by Gotan Project, Philippe Cohen Solal, Eduardo Makaroff & Christoph H. Müller",
        "Scratch (feat.Duomo)",
        "Selah",
        "Seven Nation Army by Scott Bradlee's Postmodern Jukebox",
        "Shadow Hunter by Power-Haus",
        "Shallow by Lady Gaga",
        "Silverlines (Orchestral Version) by David Damiano",
        "Sing Sing Sing by Louis Prima",
        "Stand By Me by Florence & The Machine",
        "Stairway To Heaven performed by Beth Hart",
        "Still Got the Blues by Gary Moore",
        "Still Loving You by Scorpions",
        "Survivor by 2WEI & Edda Hayes",
        "T'es où by Camille Lellouche",
        "That's It (I'm Crazy) by Sofi Tukker",
        "The Beat Hip Hip Chin Chin (Samba) by Watazu",
        "The Feeling Begins by Peter Gabriel",
        "The Firebird Suite (Excerpt) by Isakson Foundation Music Collective",
        "The Game Is Afoot by Eternal Eclipse",
        "The Lost Crown by 2WEI, Josnez and Kataem",
        "The Power by Snap!",
        "The Question of You by Prince",
        "The Sounds of Nightmares by Tobias Lilja",
        "They Don't Care About Us by Michael Jackson",
        "This Is War by Matthew Raetzel, Richard Farrell",
        "Time To Say Goodbye performed by Sarah Brightman, Andrea Bocelli",
        "Trace of Living by Han Yong Chol",
        "Twisted Nerve by Bernard Herrmann",
        "Unchained Melody by Roy Orbison",
        "Univeral Fanfare by The Minions",
        "Uptown Funk by Bruno Mars",
        "Vicious Funk by Hector Pereira",
        "Voila by Barbara Pravi",
        "Wake of Death (Reunited) by Guy Farley",
        "Waltz by Mgzavrebi, Gigi Dedalamazishvili",
        "Watergun by Remo Forrer",
        "Witchdoctor by Camo & Krooked",
        "Yellow Moon by Luca D'Alberto",
        "Yesterday by Michael Bolton, Paul McCartney, John Lennon",
        "You? by Two Feet",
        "Young and Beautiful by Lana Del Rey",
        "Zip Gun Bop by Royal Crown Revue",
    ],
}

In [ ]:
df_fs_exploded[df_fs_exploded['Song'].str.contains('Oogway Ascends')]

     Skater Name                           Song
232  Yudong CHEN  Oogway Ascends by Hans Zimmer

In [ ]:
df_sp_exploded.to_csv('song_list_sp.csv')

In [ ]:
df_fs_exploded.to_csv('song_list_fs.csv')

In [ ]:
df_sp_exploded

           Skater Name                                               Song
0            LIU Alysa                                  Promise by Laufey
1       SAKAMOTO Kaori  Time To Say Goodbye performed by Sarah Brightm...
2            NAKAI Ami                             La Strada by Nino Rota
3           CHIBA Mone  Last Dance by Donna Summer, Giorgio Moroder, P...
4          GLENN Amber                           Like A Prayer by Madonna
..                 ...                                                ...
312        Kevin AYMOZ                        Le Lac by Jean-Michel Blais
312        Kevin AYMOZ                                 Judas by Lady Gaga
313  Alexander ZLATKOV  Nureyev (from “The White Crow”) by Lisa Batias...
314        David SEDEJ  Asturias (from Suite Española) by The Six Stri...
314        David SEDEJ                                   Carmen by Marcin

[434 rows x 2 columns]

# Utilizing apply function to map category in the dataframe.

In [ ]:
def categorize_song(song):
    for category, keywords in sp_mapping.items():
        for keyword in keywords:
            if keyword.lower() in song.lower():
                return category
    return 'Uncategorized'  # Default category for songs that don't match

# Apply the categorization function
df_sp_exploded['Category'] = df_sp_exploded['Song'].apply(categorize_song)

# Display the resulting DataFrame
print(df_sp_exploded)

           Skater Name                                               Song  \
0            LIU Alysa                                  Promise by Laufey
1       SAKAMOTO Kaori  Time To Say Goodbye performed by Sarah Brightm...
2            NAKAI Ami                             La Strada by Nino Rota
3           CHIBA Mone  Last Dance by Donna Summer, Giorgio Moroder, P...
4          GLENN Amber                           Like A Prayer by Madonna
..                 ...                                                ...
312        Kevin AYMOZ                        Le Lac by Jean-Michel Blais
312        Kevin AYMOZ                                 Judas by Lady Gaga
313  Alexander ZLATKOV  Nureyev (from “The White Crow”) by Lisa Batias...
314        David SEDEJ  Asturias (from Suite Española) by The Six Stri...
314        David SEDEJ                                   Carmen by Marcin

             Category
0    pop_contemporary
1    pop_contemporary
2            warhorse
3    pop_contemporary
4    pop_contemporary
..                ...
312  pop_contemporary
312  pop_contemporary
313     movie/musical
314          warhorse
314          warhorse

[434 rows x 3 columns]

# Doing the same for free skate music

In [ ]:
fs_mapping = {
    'warhorse': [
        "2nd Piano Concerto (Il. Adagio sostenuto) by Sergei Rachmaninov, HAUSER, London Symphony Orchestra, Robert Ziegler, Arr. Robert Smith",
        "Adagio by Katherine Jenkins, Remo Giazotto,Tomaso Albinoni, Dave Pickell, Jeremy Lubbock",
        "Adagio for Strings by Samuel Barber",
        "Adiemus (Adiemus: Songs of Sanctuary) by Karl Jenkins, Mike Ratledge",
        "Bacchanale from Samson and Delilah by Camille Saint-Saens, Silvio Varviso, Dresden Staatskapelle",
        "Balada para un Loco by Milva, Astor Piazzolla, NAR International",
        "Boléro, m. 81 by Maurice Ravel",
        "Butterfly Lovers Violin Concerto by Gang Chen, Zhanhao He",
        "Carmen Suite No. 1 (Arr. E. Guiraud) by George Bizet",
        "Cinema Paradiso by Ennio Morricone",
        "Clair de Lune by Claude Debussy arranged by Maxime Rodriguez",
        "Clair de Lune by Claude Debussy, Cody Fry",
        "Claire de lune",
        "Clouds, The Mind on the (Re) Wind by Ezio Bosso",
        "Elegy Op. 3 No. 1 (Morceaux de Fantaisie) by Sergei Rakhmaninov",
        "Experience by Ludovico Einaudi, Daniel Hope, I Virtuosi Italiani",
        "Gayane Suite No. 2: III. Dance of the Boys \xa0by Aram Khachaturian, André Anichanov & St. Petersburg State Symphony Orchestra",
        "Gayane Suite No. 2: V. Lullaby by Aram Khachaturian, André Anichanov & St. Petersburg State Symphony Orchestra",
        "Gayane Suite No. 2: VI Sabre Dance \xa0by Aram Khachaturian, André Anichanov & St. Petersburg State Symphony Orchestra",
        "Gayane Suite No. 3: V. Solo - Love Duet \xa0by Aram Khachaturian, André Anichanov & St. Petersburg State Symphony Orchestra",
        "Hymn (Adiemus: Songs of Sanctuary) by Karl Jenkins, Mike Ratledge",
        "I Giorni by Daniel Hope, Ludovico Einaudi",
        "In Caelum Fero (Adiemus: Songs of Sanctuary) by Karl Jenkins, Mike Ratledge",
        "Introduction and Rondo Capriccioso for Violin and Orchestra in A Minor, Op. 28 by Camille Saint Saens",
        "Invierno Porteno by Astor Piazzolla",
        "Liebestraum by Franz Liszt",
        "Mon coeur s'ouvre à ta voix by Camille Saint-Saens, Sissel",
        "No! Pagliaccii no son by Ruggero Leoncavallo",
        "Nocturne No. 1 in D Minor by Jon Batiste",
        "Nuvole Bianche by Ludovico Einaudi",
        "Oblivion by Astor Piazzolla",
        'Pagliacci, Act I: "Recitar!.Vesti la giubba" by Ruggero Leoncavallo, Luciano Pavarotti',
        "Pagliacci: Intermezzo by Ruggero Leoncavallo",
        "Pagliacci: No., Pagliaccio non son.Suvvia, cosi terribile by Ruggero Leoncavallo, Luciano Pavarotti",
        "Piano Concerto No. 2, Op. 18: I. Moderato by Sergei Rachmaninov, Anna Fedorova, Sinfonieorchester St. Gallen, Modestas Pitrena",
        "Prelude in C sharp minor (Morceaux de Fantaisie) by Sergei Rakhmaninov",
        "Preludio by Ruggero Leoncavallo",
        "Rain Dance (Adiemus III: Dances of Time) by Karl Jenkins, Mike Ratledge",
        "Rain, In Your Black Eyes by Ezio Bosso",
        "Rain, in Your Black Eyes by Ezio Bosso",
        "Samson et Dalilah Act 1: Dieu! Dieu d'Israel by Camille Saint-Saens",
        "Samson et Dalilah: Bacchanale by Camille Saint-Saens",
        "Scheherazade by Nikolai Rimsky-Korsakov",
        "Spartacus Suite No. 2: I. Adagio Of Spartacus And Phrygia by Aram Khatchaturian",
        "Suvvia, Coserribile by Ruggero Leoncavallo",
        "Swan Lake, Op. 20, Act 4: No. 28, Allegro agitato - Molto meno mosso - Allegro vivace by Petr I. Tchaikovski",
        "Swan Lake, Op.20, Act IV: 29. Finale (Andante - Allegro agitato - Alla breve - Moderato e maestoso by Petr I. Tchaikovski",
        "Swan lake, Op20; Act 1: No.4, Pas de trois - I. Intrada (Allegro) by Petr I. Tchaikovski",
        "The American Four Seasons by Philip Glass",
        "The Nutcracker Suite by P. I. Tchaikovski",
        "Tirol Concerto: Movement II by Philip Glass, arr. by Cedric Tour",
        "Tintinnabulum (Adiemus: Songs of Sanctuary) by Karl Jenkins",
        "Turandot: Christopher Tin Finale",
        'Un giorno per noi (A Time For Us from "Romeo and Juliet") by Nino Rota, performed by Josh Groban',
        "Vesti la giubba by Ruggero Leoncavallo",
        "Yo Soy Maria by Astor Piazzolla, performed by Milva",
    ],
    'movie/musical': [
        "007 (James Bond Theme) (epic trailer version)",
        "007 James Bond Theme (epic version)",
        '160 BPM (from "Angels and Demons" soundtrack) by Hans Zimmer, Nick Glennie-Smith, Joshua Bell',
        '503 (from "Angels and Demons" soundtrack) by Hans Zimmer, Nick Glennie-Smith',
        'A Thousand Times Goodnight (from "Romeo and Juliet" soundtrack) by Abel Korzeniowski',
        'A World of Your Own (from "Wonka" soundtrack) by Timothée Chalamet & The Cast of Wonka',
        "Across the Stars (Love Theme from \u201dStar Wars: Attack of the Clones\u201d) by John Williams",
        "Across the Stars (from \u201dStar Wars: Attack of the Clones\u201d) by Julian Riem",
        "Across the Stars (from \u201dStar Wars: Attack of the Clones\u201d) \xa0by Julian Riem",
        'Air (from "Angels and Demons" soundtrack) by Hans Zimmer, Nick Glennie-Smith',
        'Ascent (from "I Medici" soundtrack) by Paolo Buonvino',
        "Audition - The Fools Who Dream (La La Land soundtrack) by Justin Hurwitz, Emma Stone, Benj Pasek, Justin Paul",
        'Castells (from "Human" soundtrack) by Armand Amar',
        "Come What May (from Moulin Rouge)",
        "Confessa - The Diva Dance by Dimash, Eric Serra",
        'Dam in China (from "Human" soundtrack) by Armand Amar',
        'Dance Of The Firebird (from "The Firebird") by Igor Stravinski',
        "Dark (X-Men Dark Phoenix soundtrack) by Hans Zimmer",
        "Deletion (X-Men Dark Phoenix soundtrack) by Hans Zimmer",
        "Dragon Heart (soundtrack) by Randy Edelman",
        "Dracula The Musical by Frank Widhorn, Don Black & Christopher Hampton",
        "Dune Theme Epic Trailer Version (Paul\u2019s Dream) by Hans Zimmer",
        "Eleanor Rigby by Cody Fry arr. by Cédric Tour",
        "Eleanor Rigby by The Beatles, Cody Fry",
        'Entr\'acte (from "Sunset Boulevard") by Andrew Lloyd Webber',
        "Epilogue (La La Land soundtrack) by Justin Hurwitz",
        "Epilogue \xa0(La La Land soundtrack) by Justin Hurwitz",
        'Finale (from "Kingsman: The Secret Service" soundtrack) by Henry Jackman & Matthew Margeson',
        'Finale (from "The Firebird") by Igor Stravinski',
        "Finale X by Brian Tyler",
        'Finale: Sun & Moon (Reprise) (from "Miss Saigon") by Claude-Michel Schönberg',
        "Frameshift (X-Men Dark Phoenix soundtrack) by Hans Zimmer",
        'From Russia With Love ("James Bond" soundtrack)',
        "Gap (X-Men Dark Phoenix soundtrack) by Hans Zimmer",
        'George Valentine (from "The Artist" soundtrack) by Ludovic Bource',
        "Ghost -The Musical by Glen Ballard, Alex North, Bruce Joel Rubin, Hy Zaret",
        "Gladiator II Overture by Harry Gregson-Williams",
        "Gladiator by Hans Zimmer",
        'Hard to Starboard (from "Titanic" soundtrack) by James Horner',
        "Heart of a King (The Man in the Iron Mask soundtrack) by Nick Glennie-Smith",
        'I Dreamed a Dream (from "Les Miserables") by Anne Hathaway, Claude Michel Schoenberg',
        'Infernal Dance of King Kaschei (from "The Firebird") by Igor Stravinski',
        "Insertion (X-Men Dark Phoenix soundtrack) by Hans Zimmer",
        "Interstellar by Hans Zimmer, performed by Imperial Orchestra",
        "Jaws (soundtrack) by John Williams & The City of Prague Philharmonic Orchestra",
        "Joker Theme (Epic Version - Call me Joker) Folie à Deux by Hildur Guðnadóttir, Vince Cox",
        "Joker Theme; Rock & Roll (Part 2) by Gary Glitter, BATJAX",
        "Joker: Folie à Deux by Hildur Guðnadóttir",
        'Kissing You (Love Theme from "Romeo and Juliet") by Craig Armstrong',
        "Les Parapluies de Cherbourg (The Umbrellas of Cherbourg) by Michel Legrand",
        "Light of the Seven (Game of Thrones soundtrack) by Ramin Djawadi",
        'Lorenzo The Magnificient (from "I Medici" soundtrack) by Paolo Buonvino',
        'Love for Duty (from "I Medici" soundtrack) by Paolo Buonvino',
        'Manners Maketh Man (from "Kingsman: The Secret Service" soundtrack) by Henry Jackman & Matthew Margeson',
        "Mia & Sebastian's Theme - Late for the Date (La La Land soundtrack) by Justin Hurwitz",
        "Mission Impossible Live by Adam Clayton, Larry Mullen",
        'My Heart Will Go On (from "Titanic" soundtrack) by Celine Dion, James Horner, Will Jennings',
        "My Road Leads Into the Desert (Dune soundtrack) by Hans Zimmer",
        "Night of Terror (Black Swan soundtrack) by Clint Mansell",
        "Now We are Free by Hans Zimmer, performed by 2Cellos",
        'Nureyev (from "The White Crow") by Ilan Eshkeri, Lisa Batiashvili',
        "Onegin (soundtrack) by Georgiy Zheryakov",
        "Oogway Ascends by Hans Zimmer",
        'Opening Theme from "Stranger Things"',
        'Overture -The Heat Is On in Saigon (from "Miss Saigon") by Claude-Michel Schönberg',
        'Overture of Conclave (from "Conclave" soundtrack) by Volker Bertelmann',
        'Paddy Fields (from "Human" soundtrack) by Armand Amar',
        "Paul's Dream (The Dune Sketchbook, soundtrack) by Hans Zimmer",
        'Peppy and George (from "The Artist" soundtrack) by Ludovic Bource',
        "Perfection (Black Swan soundtrack) by Clint Mansell",
        "Poor Things (soundtrack) by Jerskin Fendrix, Carminho",
        'Postlude of Conclave (from "Conclave" soundtrack) by Volker Bertelmann',
        "Princess Mononoke by Joe Hisaishi",
        'Pure Imagination (from "Wonka" soundtrack) by Timothée Chalamet',
        "Raoul and Christine (The Man in the Iron Mask soundtrack) by Nick Glennie-Smith",
        'Renaissance (from "I Medici" soundtrack) by Paolo Buonvino & Skin',
        "Rhapsody on Bond, (James Bond - epic piano solo) by Charles Szczepanek",
        'Rose (from "Titanic" soundtrack) by James Horner',
        'Round Dance of the Princesses (from "The Firebird") by Igor Stravinski',
        'Scrub Scrub (from "Wonka" soundtrack) by The Cast of Wonka',
        'Second Day (from "Conclave" soundtrack) by Volker Bertelmann',
        "Singing in the Rain by Ju Firebird, Gene Kelly",
        "Someone in the Crowd (La La Land soundtrack) by Justin Hurwitz, Emma Stone, Callie Hernandez, Sonoya Mizuno, Jessica Rothe, Benj Pasek, Justin Paul",
        "Song of the Sisters (The Dune Sketchbook, soundtrack) by Hans Zimmer",
        'Soon Enough (from "Conclave" soundtrack) by Volker Bertelmann',
        "Sparkling Diamonds (from Moulin Rouge)",
        "Speak Softly Love (The Godfather soundtrack) by Nino Rota",
        "Stumbled Beginnings \u2026 (Black Swan soundtrack) by Clint Mansell",
        "Suite from Lawrence Of Arabia",
        "Surrounded (The Man in the Iron Mask soundtrack) by Nick Glennie-Smith",
        "Tarantella (The Godfather soundtrack) by Nino Rota",
        'Tears (from "Conclave" soundtrack) by Volker Bertelmann',
        'The American Dream (from "Miss Saigon") by Claude-Michel Schönberg',
        "The Artist (soundtrack) by Ludovic Bource",
        "The Blue Planet (Blue Planet II soundtrack) by Jacob Shae, Hans Zimmer, David Fleming, George Fenton",
        'The Conclave Procession (from "I Medici" soundtrack) by Paolo Buonvino',
        'The Diva Dance (from "The Fifth Element" soundtrack) by Eric Serra',
        "The Dune Sketchbook (music from the soundtrack) by Hans Zimmer",
        "The Fall of Saigon \xa0(from \"Miss Saigon\") by Claude-Michel Schönberg",
        'The Final Scene (from "Sunset Boulevard") by Andrew Lloyd Webber',
        "The Godfather Waltz (The Godfather soundtrack) by Nino Rota, Carmine Coppola",
        "The Handmaiden by Chan-Wook Park",
        "The Immigrant (The Godfather soundtrack) by Carmine Coppola, Nino Rota",
        "The Legend of Ashitaka by Joe Hisaishi",
        'The Love Inside (from "Ghost - The Musical")',
        "The Mission (soundtrack) by Ennio Morricone, arranged by Cedric Tour",
        'The Sacred Bird (from "Miss Saigon") by Claude-Michel Schönberg performed by Lea Salonga',
        "The Shark Approaches (Jaws soundtrack) by John Williams",
        'The World Is Not Enough (from "James Bond" soundtrack) by Don Black, David George Arnold',
        "Themyscira (Wonder Woman Soundtrack) by Hans Zimmer",
        "They Long To Be (Close To You) Joker: Folie à Deux by Lady Gaga, Joaquin Phoenix, Richard Carpenter",
        'This Is the Hour (from "Miss Saigon") by Claude-Michel Schönberg',
        "Time (soundtrack) by Hans Zimmer",
        "Titanic Suite \xa0by James Horner",
        'Toil (from "Human" soundtrack) by Armand Amar',
        'Unchained Melody (from "Ghost - The Musical")',
        'Valentine (from "Kingsman: The Secret Service" soundtrack) by Henry Jackman & Matthew Margeson',
        'Walk Through Rain (from "Conclave" soundtrack) by Volker Bertelmann',
        "War (from \"I Medici\" soundtrack) \xa0by Paolo Buonvino",
        'With One Look (from "Sunset Boulevard") by Andrew Lloyd Webber',
        "Wonder Woman Main Theme (Wonder Woman soundtrack) by Hans Zimmer, Tina Guo, Junkie XL",
    ],
    'pop_contemporary': [
        "A Grand Finish by Kris Bowers",
        "A little Less Conversation by Elvis Presley, Junkie XL",
        "Adagio For Strings And Storm by Nico Cartosio",
        "Ancient Middle Eastern Female Vocal by Rafael Krux & Andrea Krux",
        "Arcade by Duncan Laurence, Oscar Holleman, Wouter Hardy",
        "Archangel by Two Step From Hell, Thomas Bergersen",
        "Au fil du temps by Karl Hugo",
        "Aviation Schism by Brian Tyler",
        "Believer by Imany",
        "Bonfire by Lauri Porra",
        "Brick & Blood by The Newton Brothers",
        "Call me Simon by Kris Bowers",
        "Can't Take My Eyes Off You by Piano Dust Covers",
        "Code Duello by Power-Haus, Sergiu-Dan Muresan",
        "Creep by Vincint Cannady",
        "David\u2019s Writings by Christopher Willis",
        "Dawn of Faith by Eternal Eclipse",
        "Defend This Land by Kim Hyok Chol",
        "Demimonde by Varese Sarabande",
        "Devouring Passion by Karl Hugo",
        "Dynasties Clash by Or Chausha",
        "Défilé 1962 by Ibrahim Maalouf",
        "Earth Melodies by Ekaterina Shelehova",
        "Eastern Intro by Jeff Van Dyck",
        "Enemy of Truth by Jung Se Rin",
        "Epic Middle Eastern Vocal Trailer by Rafael Krux & Andrea Krux",
        "Escapes Within by Adam Taylor, Elisabeth Moss",
        "Fantasy of Happiness",
        "Fast X by Brian Tyler",
        "Fates Illumination by Matthew Chastney",
        "Feeling Good by Michael Buble",
        "Forgotten Odes (soundtrack) by Eternal Eclipse -",
        "Forgotten Sins by Audiomachine & Harry Lightfoot - Harry Lightfoot",
        "Get Back by The Beatles arr. by \xa0Cédric Tour",
        "Ghosts by Clint Mansell, Kronos Quartet",
        "Good News by Apashe",
        "Hallelujah by The Canadian Tenors, Leonard Cohen",
        "Halston by Stephan Moccio",
        "Holocene by Bon Iver",
        "Hole up 'Til Sunrise by Ludwig Goransson",
        "How Deep Is Your Love (Serban Mix) by Bee Gees",
        "Hymne a l\u2019amour",
        "Hymne à l'amour by Patricia Kaas, Édith Piaf",
        "I Belong to You (Mon coeur s'ouvre a ta voix) by Muse",
        "I Lied to You by Miles Caton",
        "I Will Find You by Audiomachine",
        "If You Go Away by Imany",
        "In This Shirt by The Irrepressibles",
        "Interview with a Vampire",
        "It's All Coming Back To Me Now by Celine Dion",
        "It's Raining Men by The Weather Girls",
        "I\u2019m Kissing You (Radio Edit) by Des\u2019ree, Timothy Atack",
        "I\u2019m Tired (Long Version) by Labrinth, Zendaya",
        "I\u2019m Tired (ft. Zendaya) Bonus Track by Labrinth, Zendaya",
        "JIN by Yu Takami, Seika Nagaoka",
        "Jailhouse Rock by Elvis Presley",
        "Journey through the Orient:",
        "Judge Jury Executioner by Power Haus, Berlin Aires",
        "La Alegria by Yasmin Levy",
        "La Terre Vue du Ciel by Armand Amar",
        "La terre vue du ciel by Armand Amar",
        "La vie en rose by Patricia Kaas, Édith Piaf",
        "Lay My Body Down (Orchestra Version) by Rag'n'Bone Man",
        "Let It Be by JP Cooper \xa0arr. by Cedric Tour",
        "Lion Theme by Dustin O\u2018Halloran",
        "Love Like Ghosts by Lord Huron",
        "Lucy Gray (part 1) by Rachel Zegler, William Wordsworth",
        "Lullaby by Andrea Farri, Valentina Costanzo",
        "Lux Aeterna by Clint Mansell, Kronos Quartet",
        "Lux Aeterna from Requiem for a Dream (Epic Version) by Clint Mansell, L'Orchestra Cinematique",
        "Lux Aeterna from Requiem for a Dream (Extended Instrumental Version) by Clint Mansell, NPT Music",
        "L'immensità (2015 Version) by Il Volo",
        "MacArthur Park Suite by Donna Summer",
        "Macho Man by Village People",
        "Mahogany Session by Jacob Banks",
        "Maison by Emilio Piano ft. Lucie",
        "Maison by Emilio Piano, Lucie",
        "Mala Luna by Gino Vannelli",
        "Marvel's Daredevil: Born Again (Main Theme) by The Newton Brothers",
        "Matador by Bernardo Bonezzi",
        "Meet Me in the Woods by Lord Huron",
        "Melting Waltz by Varese Sarabande",
        "Mercy Duet by Max Richter, Ros Stephen",
        "Mercy Voiceless by Max Richter, Ros Stephen",
        "Middle Eastern by India Happy",
        "Morningrise by Harry Lightfoot, Audiomachine",
        "My Funny Valentine by Michael Buble",
        "My Perception of Love by Benjamin Amaru",
        "My Sweet and Tender Beast by Evgeni Doga",
        "My Way by Elvis Presley",
        "My Way by Frank Sinatra",
        "My Way for Donovan by Cédric Tour",
        "Myrskyluodon Maija by Lauri Porra",
        "Nevertheless She Persisted by Audiomachine, Samuel Karl Bohn",
        "No More Fight Left in Me by Armand Amar feat. Imany",
        "No Redemption by Gothic Storm",
        'Nocturne in D-Flat Major "Un Reve" by Eric Christian',
        "Non, je ne regrette rien by Patricia Kaas, Édith Piaf",
        "Not Alone Anymore by Armand Amar",
        "Nothing Else Matters by Metallica performed by The Rock Orchestra, Halocene",
        "Oratores by Apashe",
        "Original Composition by Karl Hugo",
        "Photograph by Cliff Masterson, Cody Fry",
        "Photograph by Cody Fry arranged by Maxime Rodriguez",
        "Quando l'amore diventa poesia (Cover Audio) by Il Volo",
        "Rain by Tony Ann",
        "Really Slow Motion Human by Rag'n'Bone Man (Epic Cover)",
        "Redemрtion by Eternal Ecliрse",
        "Refuge by Max Ricjter, Ros Stephen",
        "Rise Like a Рhoenix by Conchita Wurst",
        "Roman Boots by Or Chausha",
        "Roses by Jean-Michal Blais",
        "Run With Your Heart by Dream Cave, Johannes Bornlöf",
        "Runaway by Aurora",
        "Sail by Awolnation, Aaron Bruno",
        "Say Something (A Great Big World)",
        "See You Again by Henry Lau",
        "Senses by Cédric Tour",
        "Shadows Over Persia by Hakan Glante",
        "Shakuhachi by Armad Amar, Suizan J. F-Lagrost, (Shakuhachi Flute) & The City of Prague Philharmonic Orchestra",
        "Shot by The Rasmus",
        "Should It Be This Hard? by \xa0Evelyn Bates",
        "Shout by Tears For Fears, Roland Orzabal",
        "So Far by Olafur Arnalds featuring Arnor Dan",
        "Spring 1 - 2012 by Max Richter, Andre de Ridder, Daniel Hope",
        "Starfall by Marc Hanania",
        "Stayin' Alive (Serban Mix) by Bee Gees",
        "Story Of A March Day by Cédric Tour",
        "Summer Overture by Clint Mansell",
        "T'es où by Camille Lelouche",
        "That Home by Cinematic Orchestera",
        "That's Life by, Frank Sinatra, Ernie Freeman",
        "The Ball by Asaf Avidan",
        "The Creation of Adam:",
        "The End by JPOLND",
        "The Feels by Labrinth, Zendaya",
        "The Gallows by Audiomachine",
        "The Good Egg - A Vintage Merrie Melodie by Carl Stalling",
        "The Great Adventure by Rok Nardin",
        "The Grotto by Audiomachine",
        "The Longest Night In Limbo by Nico Cartosio",
        "The Mad Prince by Rok Nardin",
        "The Night We Met by Lord Huron",
        "The Return by Clann",
        "The Smell of the Sea by Alan Mayer",
        "The Storm by Balázs Havasi",
        "The Tear Maker by Andrea Farri",
        "The Wicked Ones by Secession Studios & Greg Dombrowski",
        "This Place Was a Shelter by Ólafur Arnalds",
        "To Build A Home by The Cinematic Orchestra",
        "To Build a Home by Cinematic Orchestra",
        "Torn by Nathan Lanier",
        "Trouble by Austin Butler",
        "Turning Page by Daniel Hart performed by Starr Andrews",
        "Twiling Huntress feat. Merethe Soltvedt",
        "Una Noche Mas by Yasmin Levi, Yechel Hasson, Alvaro Garrido, Miles Danso",
        "Verve by Ryan Taubert, FJORA, Alexandra Petkovski",
        "Warriors by 2WEI",
        "What a Wonderful World by Lexi Walker, The Piano Guys",
        "While My Guitar Gently Weeps by The Beatles arr. by Cédric Tour",
        "Whisperers from the Heart by Karl Hugo",
        "White Flowers Take Their Bath by Meredi, Mari Samuelsen, Scoring Berlin, Jonathan Stockhammer",
        "Wings by Birdy, Jasmine Van Den Bogaerde, Ryan Tedder",
        "Y.M.C.A by Village People",
        "Yo Viviré by J2 (feat. Ilza)",
        "You Should Be Dancing (Serban Mix) by Bee Gees",
        "Öldurot by Olafur Arnalds featuring Atli Örvarsson and SinfoniaNord",
        "Perfect Symphony",
    ],
}

In [ ]:
def categorize_fssong(song):
    for category, keywords in fs_mapping.items():
        for keyword in keywords:
            if keyword.lower() in song.lower():
                return category
    return 'Uncategorized'  # Default category for songs that don't match

# Apply the categorization function
df_fs_exploded['Category'] = df_fs_exploded['Song'].apply(categorize_fssong)

# Display the resulting DataFrame
df_fs_exploded

           Skater Name                                               Song  \
0            LIU Alysa               MacArthur Park Suite by Donna Summer
1       SAKAMOTO Kaori        La vie en rose by Patricia Kaas, Édith Piaf
1       SAKAMOTO Kaori       Hymne à l'amour by Patricia Kaas, Édith Piaf
1       SAKAMOTO Kaori  Non, je ne regrette rien by Patricia Kaas, Édi...
2            NAKAI Ami  What a Wonderful World by Lexi Walker, The Pia...
..                 ...                                                ...
311     Alp Eren OZKAN    From Russia With Love ("James Bond" soundtrack)
312        Kevin AYMOZ                     Boléro, m. 81 by Maurice Ravel
313  Alexander ZLATKOV                         Mala Luna by Gino Vannelli
314        David SEDEJ                  The Great Adventure by Rok Nardin
314        David SEDEJ                       The Mad Prince by Rok Nardin

             Category
0    pop_contemporary
1    pop_contemporary
1    pop_contemporary
1    pop_contemporary
2    pop_contemporary
..                ...
311     movie/musical
312          warhorse
313  pop_contemporary
314  pop_contemporary
314  pop_contemporary

[727 rows x 3 columns]

In [ ]:
df_fs_exploded.to_csv('free_skate_songs.csv')

In [ ]:
df_sp_exploded.to_csv('short_program_songs.csv')

In [ ]:
df_sp_exploded['Category'].value_counts()

Category
pop_contemporary    312
movie/musical        74
warhorse             48
Name: count, dtype: int64